"use strict";
module.exports = {
    'extends': ['tslint-eslint-rules'],
    'rules': {
        'adjacent-overload-signatures': true,
        'align': true,
        'arrow-parens': 'always',
        'arrow-return-shorthand': true,
        'await-promise': true,
        'block-spacing': true,
        'brace-style': [2, '1tbs', { 'allowSingleLine': true }],
        'class-name': true,
        'comment-format': [true, 'check-space'],
        'curly': true,
        'encoding': true,
        'eofline': true,
        'import-spacing': true,
        'indent': [true, 'spaces', 4],
        'label-position': true,
        'max-line-length': [true, 140],
        'member-access': true,
        'member-ordering': [
            true,
            'public-before-private',
            'static-before-instance',
            'variables-before-functions',
        ],
        'new-parens': true,
        'no-arg': true,
        'no-conditional-assignment': true,
        'no-console': true,
        'no-constant-condition': true,
        'no-construct': true,
        'no-control-regex': true,
        'no-default-export': true,
        'no-duplicate-case': true,
        'no-duplicate-imports': true,
        'no-duplicate-switch-case': true,
        'no-duplicate-super': true,
        'no-duplicate-variable': true,
        'no-empty': true,
        'no-empty-character-class': true,
        'no-eval': true,
        'no-extra-semi': true,
        'no-implicit-dependencies': [true, 'optional', 'dev'],
        'no-inferrable-types': true,
        'no-inner-declarations': true,
        'no-invalid-regexp': true,
        'no-invalid-template-strings': true,
        'no-invalid-this': true,
        'no-irregular-whitespace': true,
        'no-misused-new': true,
        'no-multi-spaces': true,
        'no-redundant-jsdoc': true,
        'no-reference': true,
        'no-return-await': true,
        'no-regex-spaces': true,
        'no-shadowed-variable': true,
        'no-string-literal': true,
        'no-string-throw': true,
        'no-switch-case-fall-through': true,
        'no-this-assignment': [true, { 'allow-destructuring': true }],
        'no-unexpected-multiline': true,
        // it's buggy: https://github.com/palantir/tslint/issues/2430#issuecomment-345961338
        // 'no-unnecessary-callback-wrapper': true,
        'no-unnecessary-initializer': true,
        'no-unnecessary-qualifier': true,
        'no-unused-expression': [
            true,
            'allow-fast-null-checks',
            'allow-new',
        ],
        'no-var-keyword': true,
        'number-literal-format': true,
        'object-curly-spacing': [
            true,
            'always',
        ],
        'object-literal-shorthand': true,
        'one-line': true,
        'one-variable-per-declaration': true,
        'ordered-imports': true,
        'prefer-const': true,
        'prefer-object-spread': true,
        'prefer-template': [
            true,
            'allow-single-concat',
        ],
        'quotemark': [
            true,
            'single',
            'jsx-single',
            'avoid-escape',
            'avoid-template',
        ],
        'radix': true,
        'return-undefined': true,
        'semicolon': [
            true,
            'always',
        ],
        'switch-default': true,
        'trailing-comma': [
            true,
            {
                'multiline': {
                    'arrays': 'always',
                    'objects': 'always',
                    'imports': 'always',
                    'exports': 'always',
                    'typeLiterals': 'always'
                },
                'esSpecCompliant': true
            },
        ],
        'triple-equals': true,
        "type-literal-delimiter": true,
        'typedef-whitespace': [
            true,
            {
                'call-signature': 'nospace',
                'index-signature': 'nospace',
                'parameter': 'nospace',
                'property-declaration': 'nospace',
                'variable-declaration': 'nospace'
            },
        ],
        'unified-signatures': true,
        'use-isnan': true,
        'valid-typeof': true,
        'whitespace': [
            true,
            'check-branch',
            'check-decl',
            'check-operator',
            'check-module',
            'check-separator',
            'check-rest-spread',
            'check-type',
            'check-type-operator',
            'check-preblock',
            'check-rest-spread',
        ]
    }
};
